# Generated by Django 3.2.6 on 2021-08-27 11:53

from django.db import migrations, models

from carseller_app.models import User, Region


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carbodytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbodyname', models.CharField(blank=True, db_column='CarBodyName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'carbodytype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(blank=True, db_column='ModelName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'carmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, db_column='State', max_length=45, null=True)),
            ],
            options={
                'db_table': 'carstate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carvender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carvendername', models.CharField(blank=True, db_column='CarVenderName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'carvender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivetype',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=45, null=True)),
            ],
            options={
                'db_table': 'drivetype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fueltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelname', models.CharField(blank=True, db_column='FuelName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'fueltype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gearboxcotype', models.CharField(blank=True, db_column='GearBoxcoType', max_length=45, null=True)),
            ],
            options={
                'db_table': 'gearbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sellrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('inginvolume', models.FloatField(blank=True, db_column='InginVolume', null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=45, null=True)),

    ],
            options={
                'db_table': 'sellrequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('surname', models.CharField(blank=True, db_column='Surname', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=45, null=True)),
                ('birthday', models.CharField(blank=True, db_column='Birthday', max_length=45, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=45, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
