# Generated by Django 3.2.6 on 2021-08-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carseller_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellrequest',
            options={'managed': False, 'ordering': ('-CreationDate',)},
        ),
    ]
