# Generated by Django 3.2.6 on 2021-08-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carseller_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellrequest',
            options={'ordering': ('-CreationDate',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('name',)},
        ),
    ]
