# Generated by Django 3.2.6 on 2021-08-28 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carseller_app', '0002_auto_20210828_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='CreationDate',
            field=models.DateTimeField(auto_now_add=True, db_column='CreationDate', null=True),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='Image',
            field=models.ImageField(blank=True, db_column='Image', default='33.jpg', null=True, upload_to='cars_imgs'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='carbodyid',
            field=models.ForeignKey(blank=True, db_column='CarBodyId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carseller_app.carbodytype'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='carmodelid',
            field=models.ForeignKey(blank=True, db_column='CarModelId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carseller_app.carmodel'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='carstateid',
            field=models.ForeignKey(blank=True, db_column='CarStateId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carseller_app.carstate'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='drivetypeid',
            field=models.ForeignKey(blank=True, db_column='DriveTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carseller_app.drivetype'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='fueltypeid',
            field=models.ForeignKey(blank=True, db_column='FuelTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carseller_app.fueltype'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='gearboxid',
            field=models.ForeignKey(blank=True, db_column='GearBoxId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carseller_app.gearbox'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='region',
            field=models.ForeignKey(blank=True, db_column='Region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carseller_app.region'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='UserId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carseller_app.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='Author',
            field=models.ForeignKey(blank=True, db_column='Author', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, db_column='Region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carseller_app.region'),
        ),
    ]
