# Generated by Django 3.2.6 on 2021-08-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carseller_app', '0002_alter_sellrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellrequest',
            options={'managed': False},
        ),
    ]
