# Generated by Django 3.2.6 on 2021-08-28 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carseller_app', '0003_auto_20210828_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Author',
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='Author',
            field=models.ForeignKey(blank=True, db_column='Author', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
